openapi: 3.0.0
info:
  title: WhiteList API
  description: An API resource to whitelist IPs for various routes.
  version: 0.1.9
servers:
  - url: http://localhost:3000
paths:
  /whitelists:
    get:
      summary: 
      description: Returns a object listing of whitelisted routes and ips.
      responses:
        '200':    # status code
          description: A JSON object of whitelisted routes and ips
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status:
                    type: string
                  data: 
                    type: object
                    properties:
                      route: 
                        $ref: '#/components/schemas/Whitelist'
    post:
      summary: 
      description: Returns a object of whitelisted route of ips.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WhitelistData'
      responses:
        '201':    # status code
          description: Create a JSON object of the whitelisted route and ip
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status:
                    type: string
                  data: 
                    $ref: '#/components/schemas/Whitelist'
        '400':
          description: Validation error response
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /whitelists/remove:
    delete:
      summary: 
      description: Removes an IP from a route.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WhitelistData'
      responses:
        '200':    # status code
          description: Returns a JSON object of the whitelisted route and remaining ips
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status:
                    type: string
                  data: 
                    $ref: '#/components/schemas/Whitelist'
        '400':
          description: Validation error response
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not found error response
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /protected:
    get:
      summary: 
      description: Returns a success response if origination ip is whitelisted for this route.
      responses:
        '200':    # status code
          description: A JSON object of whitelisted routes and ips
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status:
                    type: string
                  data: 
                    type: object
                    properties:
                      message: 
                        type: string
        '400':
          description: Validation error response
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden error response
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not found error response
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /whitelists/bulk:
    post:
      summary: Whitelists a list of ips to a route
      description: Returns a object of whitelisted route of ips.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WhitelistBulkData'
      responses:
        '201':    # status code
          description: Create a JSON object of the whitelisted route and ip
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status:
                    type: string
                  data: 
                    $ref: '#/components/schemas/Whitelist'
        '400':
          description: Validation error response
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: array
      items:
        type: object
        properties:
          message:
            type: string
            required: true
            description: Appropriate error message.
          field:
            type: string
            description: Validation field where error occured.
    Whitelist:
      type: object
      properties:
        ips: 
          type: array
          items: 
            type: string
        path: 
          type: string
    WhitelistData:
      type: object
      properties:
        ip:
          type: string
        path:
          type: string
    WhitelistBulkData:
      type: object
      properties:
        ips:
          type: array
          items: 
            type: string
        path:
          type: string

